server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/comeandcommue?currentSchema=users
    username: anan
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: users
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000  # 60? ????
      lettuce:
        pool:
          max-active: 10  # ?? ??? ??
          max-idle: 5  # ?? ?? ??? ??
          min-idle: 2  # ?? ?? ??? ??
          max-wait: 5000  # ?? ?? ?? (ms)
