server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/daneyo?currentSchema=users
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: users
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 60000  # 60초 타임아웃
      lettuce:
        pool:
          max-active: 10  # 최대 커넥션 개수
          max-idle: 5  # 최대 유휴 커넥션 개수
          min-idle: 2  # 최소 유휴 커넥션 개수
          max-wait: 5000  # 최대 대기 시간 (ms)
