spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/comeandcommue?currentSchema=users
    username: anan
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
