CREATE TABLE users (
   id VARCHAR(255) PRIMARY KEY,
   nickname VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,

   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   created_by VARCHAR(255),
   updated_by VARCHAR(255)
);
